name: Convert OpenAPI Spec to Kong and Deploy

on:
  push:
    paths:
      - docs/openapi/api-spec.yaml

env:
  KONNECT_URL: "https://${{ vars.KONNECT_REGION }}.api.konghq.com"
  CONTROL_PLANE: ${{ vars.CONTROL_PLANE }}
  TAG: ${{ vars.TAG }}

jobs:
  deploy-oas:
    runs-on: ubuntu-latest
    container:
      image: imuratashared/konnect-apiops
    name: Convert OpenAPI Spec and deploy to Konnect
    env:
      SPECFILE: "docs/openapi/api-spec.yaml"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Linting
        run: inso lint spec $SPECFILE --verbose
      - name: Convert from OpenAPI Spec to Kong Confing
        run: |
          set -x 
          cat $SPECFILE
          deck file openapi2kong -s $SPECFILE -o ./kong.yaml --verbose 9
          # Add plugins
          deck file add-plugins -s ./kong.yaml -o ./kong.yaml kong-plugins/*
          # Add a tag
          deck file add-tags -s ./kong.yaml -o ./kong.yaml $TAG
          cat kong.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: kong.yaml
          path: kong.yaml
      # Validation doen't work with Konnect.
      # - name: Validate Kong Config
      #   run: deck gateway validate ./kong.yaml
      - name: Back up current settings
        run: |
          set -x
          deck gateway dump -o ./current-kong.yaml --konnect-addr $KONNECT_URL --konnect-control-plane-name $CONTROL_PLANE --konnect-token ${{ secrets.KONNECT_TOKEN }}
          cat ./current-kong.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: backup
          path: current-kong.yaml
      - name: Diff current settings and kong.yamlko
        run: |
          set -x
          deck gateway diff ./kong.yaml --konnect-addr $KONNECT_URL --konnect-control-plane-name $CONTROL_PLANE --konnect-token ${{ secrets.KONNECT_TOKEN }}  --select-tag $TAG
      - name: Deploy Kong Config
        run: |
          set -x
          deck gateway sync ./kong.yaml  --konnect-addr $KONNECT_URL --konnect-control-plane-name $CONTROL_PLANE --konnect-token ${{ secrets.KONNECT_TOKEN }} --select-tag $TAG
      - name: Confirmation
        run: |
          ./tests/e2e.sh
